name: build-test

on: [pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22.17.1
        cache: 'npm'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: typecheck
      run: yarn typecheck
    - name: test
      run: yarn test --run
    - name: build
      run: yarn ui-build
    - name: infra diff
      run: yarn infra-diff
