name: build-test

on: [pull_request]

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22.17.1
        cache: 'npm'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: typecheck
      run: yarn typecheck
    - name: test
      run: yarn test --run
    - name: build
      run: yarn ui-build
    - name: configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsCDKDeployRole
        aws-region: us-east-1
    - name: infra diff
      run: yarn infra-diff
