name: build-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        cache: 'npm'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: typecheck
      run: yarn typecheck
    - name: test
      run: yarn test --run
    - name: build
      run: yarn ui-build
    - name: infra diff
      run: yarn infra-diff
