name: build-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build
