name: deploy

on: pull_request

#on:
#  push:
#    branches:
#      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'npm'
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: install AWS CLI
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - name: build ui
        run: yarn ui-build
      - name: deploy infra
        run: yarn infra-deploy
      - name: deploy ui
        run: yarn ui-deploy
